============================= test session starts ==============================
platform linux2 -- Python 2.7.5 -- py-1.4.20 -- pytest-2.5.2
collected 2 items

test_untitled.py .F

=================================== FAILURES ===================================
_________________________________ test_answer2 _________________________________

    def test_answer2():
        '''simple example to start you off'''
        obj = untitled.Untitled()
>       assert obj.answer() == 6*9
E       assert 42 == (6 * 9)
E        +  where 42 = <bound method Untitled.answer of <untitled.Untitled instance at 0x12a7d40>>()
E        +    where <bound method Untitled.answer of <untitled.Untitled instance at 0x12a7d40>> = <untitled.Untitled instance at 0x12a7d40>.answer

test_untitled.py:11: AssertionError
====================== 1 failed, 1 passed in 0.03 seconds ======================